### ISSUE TITLE
Update the script to recalculate rewards when stakes change

### ISSUE THREAD

**Issue by Andrew-Pohl** [liquify-validation/Fuse_spark_test_script#5]
Currently if the stake of a delegate or Validator change mid cycle it will throw off the script. There are two solutions to this:

1. We query the consensus every backtested block to see if stakes have changed - this is the safest because it takes the reward calculation off the table but it also adds a lot to the run time
2. We wait for the rewards to be wrong at which point we check the consensus and see if the stakes have changed and recalculate the rewards

**Comment by leonprou** [comment]
@Andrew-Pohl I prefer the first options, unless it really slows us down (by order of magnitude).

Another question is. What we are doing when this change was spotted.
I think it makes sense to add another record to cycleData. but flag give if some flag like: midCycleChange: true. So we can spot easily spot this in the data

**Comment by Andrew-Pohl** [comment]
> @Andrew-Pohl I prefer the first options, unless it really slows us down (by order of magnitude).
> 
> Another question is. What we are doing when this change was spotted.
> I think it makes sense to add another record to cycleData. but flag give if some flag like: midCycleChange: true. So we can spot easily spot this in the data

I was thinking of making cycle data a nested dict so each change mid cycle adds a new dictionary to the current cycle data which contains the Validators new reward info, and the start and end block (kinda like a linked list I guess where the end block of n indicates a change to the next nested dict)
