### ISSUE TITLE
Refactor and add fields to cycleData.

### ISSUE THREAD

**Issue by leonprou** [liquify-validation/Fuse_spark_test_script#6]
Now the cycleData objects looks like:
```
{
		"0xBb79A903f699F2E54C970AC7ab30403A56F67804": {
			"delegators": {},
			"stakedAmount": 1000000.0,
			"selfStaked": 1000000.0,
			"fee": 0.1,
			"rewardToNode": 1556.6625155666252,
			"reward": 1556.6625155666252,
			"rewardPerBlock": 4.324063
		},
		"0xCFB72778e99886669cAD160aD73AA30F413dDeE5": {
			"delegators": {},
			"stakedAmount": 100000.0,
			"selfStaked": 100000.0,
			"fee": 0.1,
			"rewardToNode": 155.66625155666253,
			"reward": 155.66625155666253,
			"rewardPerBlock": 0.432406
		},
		"startBlock": 99398,
		"endBlock": 100117
}
```

I suggest:
```
{
	"**validators**": {
		"0xBb79A903f699F2E54C970AC7ab30403A56F67804": {
			"delegators": {},
			"stakedAmount": 1000000.0,
			"selfStaked": 1000000.0,
			"fee": 0.1,
			"rewardToNode": 1556.6625155666252,
			"reward": 1556.6625155666252,
			"rewardPerBlock": 4.324063
		},
		"0xCFB72778e99886669cAD160aD73AA30F413dDeE5": {
			"delegators": {},
			"stakedAmount": 100000.0,
			"selfStaked": 100000.0,
			"fee": 0.1,
			"rewardToNode": 155.66625155666253,
			"reward": 155.66625155666253,
			"rewardPerBlock": 0.432406
		},
		"startBlock": 99398,
		"endBlock": 100117,
		"totalStake": 1000000
	}
}
```

- moving validators to special field
- adding the totalStake

**Comment by Andrew-Pohl** [comment]
Sounds good this ties into my comments in #5 so happy to look at this at the same time too 👍

**Comment by Andrew-Pohl** [comment]
Cycle data now looks like this:

 "0": {
    "subCycleData": {
      "0": {
        "validators": {
          "0xBb79A903f699F2E54C970AC7ab30403A56F67804": {
            "delegators": {
              
            },
            "stakedAmount": 1000000.0,
            "selfStaked": 1000000.0,
            "fee": 0.1,
            "rewardToNode": 1556.6625155666252,
            "reward": 1556.6625155666252,
            "rewardPerBlock": 4.324063
          },
          "0xCFB72778e99886669cAD160aD73AA30F413dDeE5": {
            "delegators": {
              
            },
            "stakedAmount": 100000.0,
            "selfStaked": 100000.0,
            "fee": 0.1,
            "rewardToNode": 155.66625155666253,
            "reward": 155.66625155666253,
            "rewardPerBlock": 0.432406
          }
        },
        "totalStaked": 1100000.0,
        "startBlock": 100000,
        "endBlock": 100117
      }
    },
    "startBlock": 100000,
    "endBlock": 100117,
    "cycleLength": 117,
    "propagation": 0
  }
