### ISSUE TITLE
Generate a json file of in/out tx's from the validador set

### ISSUE THREAD

**Issue by leonprou** [liquify-validation/Fuse_spark_test_script#8]
It turns out that's there's no JSON RPC call for that. 
Need this for the manual checks

**Comment by Andrew-Pohl** [comment]
Can sort this do you want it as part of one of the existing jsons or a new one?

**Comment by leonprou** [comment]
@Andrew-Pohl 👍 🙏
I think makes sense that this would be a new one, hence both cycle data and results become pretty big.

**Comment by Andrew-Pohl** [comment]
Sounds good will sort that should be quick to generate just that one file 😊 (not too many transaction happening on the testnet)

**Comment by Andrew-Pohl** [comment]
@leonprou take it we also want to include delegates in this json too?

**Comment by leonprou** [comment]
@Andrew-Pohl yeah, good idea if we want to check validators we need them as well.
But I think I can work on this without the delegators

**Comment by Andrew-Pohl** [comment]
> @Andrew-Pohl yeah, good idea if we want to check validators we need them as well.
> But I think I can work on this without the delegators

Got both of them in the commit I pushed 😊🎉

**Comment by Andrew-Pohl** [comment]
Merged at commit 597360f25fe18a7ea60765e700f9d189c9adf656
